function tkrRAS_electrodes = importfile(filename, dataLines)
%IMPORTFILE Import data from a text file
%  ELECTRODESTKRRAS = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  ELECTRODESTKRRAS = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%  Example:
%  electrodestkrRAS = importfile("E:\Shares\Gershwin\Recon\PrePostSurgicalComparison\PY18N002\Pre\electrodes\electrodes_tkrRAS.tsv", [1, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 15-Jun-2020 09:26:20

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = "\t";

% Specify column names and types
opts.VariableNames = ["name", "x", "y", "z"];
opts.VariableTypes = ["char", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "name", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "name", "EmptyFieldRule", "auto");

% Import the data
tkrRAS_electrodes = readtable(filename, opts);

end